# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('roomno', models.IntegerField(primary_key=True, serialize=False)),
                ('roomtype', models.CharField(choices=[('ac', 'AC'), ('nonac', 'NonAc')], default='ac', max_length=6)),
                ('bedtype', models.CharField(choices=[('single', 'SINGLE'), ('double', 'DOUBLE')], default='single', max_length=7)),
                ('status', models.CharField(choices=[('booked', 'BOOKED'), ('available', 'AVAILABLE')], default='available', max_length=10)),
            ],
            options={
                'ordering': ('roomno',),
            },
        ),
    ]
